name: CI

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default: all_tests
        type: choice
        options:
          - all_tests
          - elements_page_test
          - alerts_frame_windows_page_test
          - interactions_page_test
          - practice_form_page_test
          - widgets_page_test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install webdriver-manager
        pip install -r requirements.txt

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        sudo apt install ./google-chrome-stable_current_amd64.deb
        google-chrome --version

    - name: all_tests
      if: "github.event.inputs.deployment_target == 'all_tests'"
      run: |
        pytest --alluredir=allure-results

    - name: elements_page_test
      if: "github.event.inputs.deployment_target == 'elements_page_test'"
      run: |
        pytest tests/elements_test.py --alluredir=allure-results

    - name: alerts_frame_windows_page_test
      if: "github.event.inputs.deployment_target == 'alerts_frame_windows_page_test'"
      run: |
        pytest tests/alerts_frame_windows_test.py --alluredir=allure-results

    - name: interactions_page_test
      if: "github.event.inputs.deployment_target == 'interactions_page_test'"
      run: |
        pytest tests/interactions_test.py --alluredir=allure-results

    - name: practice_form_page_test
      if: "github.event.inputs.deployment_target == 'practice_form_page_test'"
      run: |
        pytest tests/practice_form_test.py --alluredir=allure-results

    - name: widgets_page_test
      if: "github.event.inputs.deployment_target == 'widgets_page_test'"
      run: |
        pytest tests/widgets_test.py --alluredir=allure-results
        
    - name: Get Allure history
      uses: actions/checkout@v3
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@v1.7
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history